### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by tschirmer** [arey/mysql-client#4]
**Is your feature request related to a problem? Please describe.**
ARM support for AWS gravtion2 processors

**Describe the solution you'd like**
should be able to be achieved within the build pipeline with the following:

```
docker buildx install
docker buildx create --use
docker buildx build --platform linux/amd64,linux/arm64 . -t arey/mysql-client:latest --push
```

**Describe alternatives you've considered**
Running different nodes and running arey/mysql-client on a separate node group, this isn't ideal.

**Comment by arey** [comment]
Hi @tschirmer 
In your command, the `-platform` option accepts both platforms. Does it mean that the Docker image that will be build will support both plafforms or does the command will create 2 images?
In the first case, if you want, I could publish a new image to Docker Hub with your command line.

**Comment by tschirmer** [comment]
The command will make 2 images, but use the one tag.

When pulling via an ARM machine, it'll use the ARM image, when pulling via an x86_64 Machine, it'll just that image.

**Comment by tschirmer** [comment]
@arey That's in my experience using Kubernetes with mixed-processor technologies in it.

**Comment by arey** [comment]
Ok thanks for this precision.
I've just published the ARM images: https://hub.docker.com/repository/docker/arey/mysql-client/tags?page=1&ordering=last_updated

**Comment by tschirmer** [comment]
Great! that's working now on the graviton stack. Thanks!
